Create your personal page
BuidlGuidl/batch5.buidlguidl.com pull request #21
Opened 2024-05-15 09:28 UTC by sac1hin

## Description

_Concise description of proposed changes, We recommend using screenshots and videos for better description_

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{8}_

Your ENS/address:

2024-05-15 19:36 UTC, derrekcoleman requested changes
Hey Sachin! I like your use of icons and layout to organize the information. I left a few suggestions, all very small.

2024-05-15 19:36 UTC, derrekcoleman commented on packages/nextjs/public/builders.jpeg
Since multiple people will have pictures, please use a more descriptive name. For example, Temitope's picture is named `packages/nextjs/public/assets/temitopeohassan.jpeg`.

2024-05-15 19:36 UTC, derrekcoleman commented on packages/nextjs/app/builders/0x83DD842BB14aacE72A1a68a129D134Ee3EeBbbd4/page.tsx
> +            <Image src="/builders.jpeg" className="rounded-full" alt="Sachin Varma" width={200} height={40} />
This is a square image, so maybe you mean height={200}? Doesn't seem to affect how it's rendered, though.

2024-05-15 19:36 UTC, derrekcoleman commented on packages/nextjs/app/builders/0x83DD842BB14aacE72A1a68a129D134Ee3EeBbbd4/page.tsx
> +            <div className="text-3xl">Sachin Verma</div>
This would be a good place to use [semantic HTML](https://developer.mozilla.org/en-US/docs/Glossary/Semantics#semantics_in_html), such as an h1.

2024-05-15 19:36 UTC, derrekcoleman commented on packages/nextjs/app/builders/0x83DD842BB14aacE72A1a68a129D134Ee3EeBbbd4/page.tsx
> +          <h1 className="text-center mt-4 max-w-screen-lg leading-">
Great use of semantic HTML here. Very small note: this kind of text is probably more appropriate as an h2, rather than an h1.

2024-05-16 10:54 UTC, sac1hin commented on packages/nextjs/public/builders.jpeg
DONE

2024-05-16 10:54 UTC, sac1hin commented
All the issues i resolved

2024-05-16 20:10 UTC, derrekcoleman commented
Thanks for addressing everything! I like the addition of a rounded background, too. It helps group things on such a big, empty page.

2024-05-16 20:10 UTC, merged