Change the Logo / title / subtitle
BuidlGuidl/batch5.buidlguidl.com pull request #24
Opened 2024-05-23 14:46 UTC by sac1hin

## Description

![Screenshot from 2024-05-23 20-11-28](https://github.com/BuidlGuidl/batch5.buidlguidl.com/assets/52341319/60f64778-f876-408b-9ecd-68be9be2f863)

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #7 _

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address: 0x83DD842BB14aacE72A1a68a129D134Ee3EeBbbd4

2024-05-23 16:33 UTC, zapaz requested changes
looks great

as the logo is quite small, maybe one bigger version could be added to the center of the homepage ?

and for the title, you can change to "Batch 5 Builders Brigade"  ChatGPT idea ;-(  or something like that

2024-05-23 16:44 UTC, sac1hin commented
I have changed title

2024-05-26 09:38 UTC, technophile-04 reviewed
Nice @sac1hin !! and thanks @zapaz for suggestion !

2024-05-26 09:38 UTC, technophile-04 approved these changes

2024-05-26 09:38 UTC, merged